server:
  port: 8888
grpc:
  server:
    port: 50051

spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      access: 302400000  # 7일
      refresh: 7884000000  # 3개월

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs